[package]
name = "counter-isomorphic"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { path = "../../../leptos", default-features = false, features = ["serde"] }
leptos_router = { path = "../../../router", default-features = false }
console_log = "0.2"
gloo-net = "0.2"
log = "0.4"
console_error_panic_hook = "0.1.7"
thiserror = "1"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.0"

[features]
default = ["csr"]
csr = ["leptos/csr", "leptos_router/csr"]
hydrate = ["leptos/hydrate", "leptos_router/hydrate"]
ssr = ["leptos/ssr", "leptos_router/ssr"]