[package]
name = "hackernews-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6"
actix-web = "4"
leptos = { path = "../../../leptos", features = ["ssr"] }
log = "0.4"
hackernews-app = { path = "../hackernews-app", features = ["ssr"] }
