[package]
name = "todomvc"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { path = "../../leptos", default-features = false }
console_error_panic_hook = "0.1"
miniserde = "0.1"
log = "0.4"
console_log = "0.2"

[dev-dependencies]
wasm-bindgen-test = "0.3.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'

[features]
default = ["csr"]
csr = ["leptos/csr"]
hydrate = ["leptos/hydrate"]
ssr = ["leptos/ssr"]
