[workspace]
members = [
  # core
  "leptos",
  "leptos_dom",
  "leptos_core",
  "leptos_macro",
  "leptos_reactive",
  "leptos_server",

  # libraries
  "meta",
  "router",

  # examples
  "examples/counter",
  "examples/counter-isomorphic/client",
  "examples/counter-isomorphic/server",
  "examples/counter-isomorphic/counter",
  "examples/counters",
  "examples/counters-stable",
  "examples/fetch",
  "examples/hackernews/hackernews-app",
  "examples/hackernews/hackernews-client",
  "examples/hackernews/hackernews-server",
  "examples/parent-child",
  "examples/router",
  "examples/todomvc",
  "examples/todomvc-ssr/todomvc-ssr-client",
  "examples/todomvc-ssr/todomvc-ssr-server",
]
exclude = [
  "benchmarks",
  # not gonna lie, this is because my arm64 mac fails when linking a GTK binary
  "examples/gtk",
]


[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'
