[workspace]
members = [
  # core
  "leptos",
  "leptos_dom",
  "leptos_core",
  "leptos_macro",
  "leptos_reactive",
  "leptos_server",

  # libraries
  "meta",
  "router",

  # examples
  "examples/counter",
  "examples/counter-isomorphic/client",
  "examples/counter-isomorphic/server",
  "examples/counter-isomorphic/counter",
  "examples/counters",
  "examples/counters-stable",
  "examples/fetch",
  "examples/hackernews/hackernews-app",
  "examples/hackernews/hackernews-client",
  "examples/hackernews/hackernews-server",
  "examples/parent-child",
  "examples/router",
  "examples/todomvc",

  # book
  "docs/book/project/ch02_getting_started",
  "docs/book/project/ch03_building_ui",
  "docs/book/project/ch04_reactivity",
]
exclude = ["benchmarks"]


[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'
