[package]
name = "leptos_router"
version = "0.0.1"
edition = "2021"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/gbj/leptos"
description = "Router for the Leptos web framework."

[dependencies]
leptos_core = { path = "../leptos_core", version = "0.0.1" }
leptos_dom = { path = "../leptos_dom", version = "0.0.2" }
leptos_macro = { path = "../leptos_macro", version = "0.0.1"}
leptos_reactive = { path = "../leptos_reactive", version = "0.0.1" }
common_macros = "0.1"
itertools = "0.10"
lazy_static = "1"
linear-map = "1"
log = "0.4"
regex = { version = "1", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
bincode = "1"
url = { version = "2", optional = true }
urlencoding = "2"
thiserror = "1"
typed-builder = "0.10"
js-sys = { version = "0.3", optional = true }
wasm-bindgen = { version = "0.2", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }

[dependencies.web-sys]
version = "0.3"
features = [
	# History/Routing
	"History",
	"HtmlAnchorElement",
	"MouseEvent",
	"Url",
	# Form
	"FormData",
	"HtmlButtonElement",
	"HtmlFormElement",
	"HtmlInputElement",
	"SubmitEvent",
	"Url",
	"UrlSearchParams",
	# Fetching in Hydrate Mode
	"Headers",
	"Request",
	"RequestInit",
	"RequestMode",
	"Response",
	"Window",
]

[features]
csr = ["leptos_core/csr", "leptos_dom/csr", "leptos_macro/csr", "leptos_reactive/csr", "dep:js-sys", "dep:wasm-bindgen"]
hydrate = ["leptos_core/hydrate", "leptos_dom/hydrate", "leptos_macro/hydrate", "leptos_reactive/hydrate", "dep:js-sys", "dep:wasm-bindgen", "dep:wasm-bindgen-futures"]
ssr = ["leptos_core/ssr", "leptos_dom/ssr", "leptos_macro/ssr", "leptos_reactive/ssr", "dep:url", "dep:regex"]
transition = ["leptos_core/transition", "leptos_reactive/transition"]