[package]
name = "ch01_getting_started"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.0", features = ["csr"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'