[package]
name = "leptos_core"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos_dom = { path = "../leptos_dom" }
leptos_macro = { path = "../leptos_macro" }
leptos_reactive = { path = "../leptos_reactive" }
