[package]
name = "todomvc-ssr-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6"
actix-web = "4"
leptos = { path = "../../../leptos", features = ["ssr"] }
todomvc = { path = "../../todomvc", default-features = false, features = ["ssr"] }
