[package]
name = "leptos_meta"
version = "0.0.1"
edition = "2021"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/gbj/leptos"
description = "Tools to set HTML metadata in the Leptos web framework."

[dependencies]
leptos = { path = "../leptos", version = "0.0.4" }
log = "0.4"

[dependencies.web-sys]
version = "0.3"
features = [
	"HtmlLinkElement",
	"HtmlTitleElement"
]

[features]
csr = ["leptos/csr"]
hydrate = ["leptos/hydrate"]
ssr = ["leptos/ssr"]