[package]
name = "leptos_meta"
version = "0.1.0-alpha"
edition = "2021"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/gbj/leptos"
description = "Tools to set HTML metadata in the Leptos web framework."

[dependencies]
cfg-if = "1"
leptos = { path = "../leptos", version = "0.1.0-alpha", default-features = false }
tracing = "0.1"

[dependencies.web-sys]
version = "0.3"
features = ["HtmlLinkElement", "HtmlMetaElement", "HtmlTitleElement"]

[features]
default = ["csr"]
csr = ["leptos/csr", "leptos/tracing"]
hydrate = ["leptos/hydrate", "leptos/tracing"]
ssr = ["leptos/ssr", "leptos/tracing"]
