[package]
name = "counter"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { path = "../../leptos", features = ["csr"], version = "0.0.4" }
wee_alloc = "0.4"
console_log = "0.2"
log = "0.4"

[dev-dependencies]
wasm-bindgen-test = "0.3.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'