[package]
name = "leptos_dom"
version = "0.0.3"
edition = "2021"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/gbj/leptos"
description = "DOM operations for the Leptos web framework."

[dependencies]
js-sys = "0.3"
leptos_reactive = { path = "../leptos_reactive", version = "0.0.3" }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.31"
wee_alloc = "0.4.5"
log = "0.4"

[dependencies.web-sys]
version = "0.3"
features = [
  "Attr",
  "console",
  "Comment",
  "CssStyleDeclaration",
  "CustomEvent",
  "CustomEventInit",
  "Document",
  "DocumentFragment",
  "DomStringMap",
  "DomTokenList",
  "Element",
  "Event",
  "EventTarget",
  "HtmlCollection",
  "HtmlDivElement",
  "HtmlElement",
  "HtmlInputElement",
  "HtmlTemplateElement",
  "KeyboardEvent",
  "Location",
  "MutationObserver",
  "NamedNodeMap",
  "Node",
  "NodeList",
  "Performance",
  "ShadowRoot",
  "ShadowRootInit",
  "ShadowRootMode",
  "Storage",
  "Text",
  "TreeWalker",
  "Window"
]

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'

[features]
csr = ["leptos_reactive/csr"]
hydrate = ["leptos_reactive/hydrate"]
ssr = ["leptos_reactive/ssr"]