[package]
name = "leptos_dom"
version = "0.0.18"
edition = "2021"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/gbj/leptos"
description = "DOM operations for the Leptos web framework."

[dependencies]
cfg-if = "1"
clone-macro = "0.1"
educe = "0.4"
gloo = "0.8"
indexmap = "1.9"
itertools = "0.10"
js-sys = "0.3"
leptos_reactive = { path = "../leptos_reactive", default-features = false, version = "0.0.18" }
paste = "1"
rustc-hash = "1.1.0"
smallvec = "1"
tracing = "0.1"
typed-builder = "0.11"
wasm-bindgen = { version = "0.2", features = ["enable-interning"] }
wasm-bindgen-futures = "0.4.31"

[dependencies.web-sys]
version = "0.3"
features = [
  "Comment",
  "DomTokenList",
  "Range",
  "Text",

  # Events we cast to in leptos_macro -- added here so we don't force users to import them
  "AnimationEvent",
  "BeforeUnloadEvent",
  "ClipboardEvent",
  "CompositionEvent",
  "DeviceMotionEvent",
  "DeviceOrientationEvent",
  "DragEvent",
  "FocusEvent",
  "GamepadEvent",
  "HashChangeEvent",
  "InputEvent",
  "KeyboardEvent",
  "MouseEvent",
  "PageTransitionEvent",
  "PointerEvent",
  "PopStateEvent",
  "ProgressEvent",
  "PromiseRejectionEvent",
  "SecurityPolicyViolationEvent",
  "StorageEvent",
  "SubmitEvent",
  "TouchEvent",
  "TransitionEvent",
  "UiEvent",
  "WheelEvent",
]

[features]
default = ["web"]
web = []
csr = ["leptos_reactive/csr"]
hydrate = ["leptos_reactive/hydrate"]
ssr = ["leptos_reactive/ssr"]
stable = ["leptos_reactive/stable"]
