[package]
name = "leptos_dom"
version = "0.0.18"
edition = "2021"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/gbj/leptos"
description = "DOM operations for the Leptos web framework."

[dependencies]
cfg-if = "1"
futures = "0.3"
html-escape = "0.2"
js-sys = "0.3"
leptos_reactive = { path = "../leptos_reactive", default-features = false, version = "0.0.18" }
serde_json = "1"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.31"
log = "0.4"

[dependencies.web-sys]
version = "0.3"
features = [
  "Attr",
  "console",
  "Comment",
  "CssStyleDeclaration",
  "CustomEvent",
  "CustomEventInit",
  "Document",
  "DocumentFragment",
  "DomStringMap",
  "DomTokenList",
  "Element",
  "Event",
  "EventTarget",
  "HtmlCollection",
  "HtmlDivElement",
  "HtmlElement",
  "HtmlInputElement",
  "HtmlTemplateElement",
  "KeyboardEvent",
  "Location",
  "MutationObserver",
  "NamedNodeMap",
  "Node",
  "NodeList",
  "Performance",
  "ShadowRoot",
  "ShadowRootInit",
  "ShadowRootMode",
  "Storage",
  "Text",
  "TreeWalker",
  "Window",

  # Events we cast to in leptos_macro -- added here so we don't force users to import them
  "MouseEvent",
  "DragEvent",
  "FocusEvent",
  "KeyboardEvent",
  "ProgressEvent",
  "WheelEvent",
  "InputEvent",
  "SubmitEvent",
  "AnimationEvent",
  "PointerEvent",
  "TouchEvent",
  "TransitionEvent"
]

[dev-dependencies]
leptos = { path = "../leptos", default-features = false, version = "0.0" }
leptos_macro = { path = "../leptos_macro", default-features = false, version = "0.0" }


[features]
csr = ["leptos_reactive/csr", "leptos_macro/csr", "leptos/csr"]
hydrate = ["leptos_reactive/hydrate", "leptos_macro/hydrate", "leptos/hydrate"]
ssr = ["leptos_reactive/ssr", "leptos_macro/ssr", "leptos/ssr"]
stable = ["leptos_reactive/stable", "leptos_macro/stable", "leptos/stable"]
