[package]
name = "leptos_dom"
version = "0.0.18"
edition = "2021"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/gbj/leptos"
description = "DOM operations for the Leptos web framework."

[dependencies]
cfg-if = "1"
educe = "0.4"
gloo = "0.8"
js-sys = "0.3"
leptos_reactive = { path = "../leptos_reactive", default-features = false, version = "0.0.18" }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.31"

[dependencies.web-sys]
version = "0.3"
features = [
  "Comment",
  "Text",
  
  # Events we cast to in leptos_macro -- added here so we don't force users to import them
  "MouseEvent",
  "DragEvent",
  "FocusEvent",
  "KeyboardEvent",
  "ProgressEvent",
  "WheelEvent",
  "InputEvent",
  "SubmitEvent",
  "AnimationEvent",
  "PointerEvent",
  "TouchEvent",
  "TransitionEvent"
]

[features]
default = ["web"]
web = []
csr = ["leptos_reactive/csr"]
hydrate = ["leptos_reactive/hydrate"]
ssr = ["leptos_reactive/ssr"]
stable = ["leptos_reactive/stable"]
