[package]
name = "router"
version = "0.1.0"
edition = "2021"

[dependencies]
console_log = "0.2"
log = "0.4"
leptos = { path = "../../leptos" }
leptos_router = { path = "../../router" }
serde = { version = "1", features = ["derive"] }
futures = "0.3"

[dev-dependencies]
wasm-bindgen-test = "0.3.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'