[package]
name = "leptos_ssr"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos_reactive = { path = "../leptos_reactive" }

[features]
csr = ["leptos_reactive/csr"]
hydrate = ["leptos_reactive/hydrate"]
ssr = ["leptos_reactive/ssr"]
