[package]
name = "leptos_reactive"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
slotmap = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive", "rc"] }
elsa = "1"
wasm-bindgen = { version = "0.2", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
web-sys = { version = "0.3", optional = true, features = ["Element"] }

[dev-dependencies]
sycamore = "0.8.0-beta.7"

[features]
default = []
browser = ["dep:wasm-bindgen", "dep:wasm-bindgen-futures", "dep:web-sys"]