[package]
name = "leptos_macro"
version = "0.0.20"
edition = "2021"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/gbj/leptos"
description = "view macro for the Leptos web framework."

[lib]
proc-macro = true

[dependencies]
cfg-if = "1"
itertools = "0.10"
proc-macro-error = "1"
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full", "parsing", "extra-traits"] }
syn-rsx = "0.9"
uuid = { version = "1", features = ["v4"] }
leptos_dom = { path = "../leptos_dom", version = "0.0.20" }
leptos_reactive = { path = "../leptos_reactive", version = "0.0.20" }
leptos_server = { path = "../leptos_server", version = "0.0.20" }
lazy_static = "1.4"

[dev-dependencies]
log = "0.4"
typed-builder = "0.10"
leptos = { path = "../leptos", version = "0.0", default-features = false }
leptos_router = { path = "../router", version = "0.0 " }
serde = { version = "1", features = ["derive"] }

[build-dependencies]
rustc_version = "0.4"

[features]
default = ["ssr"]
csr = ["leptos_dom/csr", "leptos_reactive/csr", "leptos/csr"]
hydrate = ["leptos_dom/hydrate", "leptos_reactive/hydrate", "leptos/hydrate"]
ssr = ["leptos_dom/ssr", "leptos_reactive/ssr", "leptos/ssr"]
stable = ["leptos_dom/stable", "leptos_reactive/stable", "leptos/stable"]

[package.metadata.cargo-all-features]
denylist = ["stable"]
