[package]
name = "leptos_macro"
version = "0.0.7"
edition = "2021"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/gbj/leptos"
description = "view macro for the Leptos web framework."

[lib]
proc-macro = true

[dependencies]
proc-macro-error = "1"
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full", "parsing", "extra-traits"] }
syn-rsx = "0.8.1"
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
leptos_core = { path = "../leptos_core" }
leptos_dom = { path = "../leptos_dom" }
leptos_reactive = { path = "../leptos_reactive" }
log = "0.4"

[features]
default = ["ssr"]
csr = ["leptos_core/csr", "leptos_dom/csr", "leptos_reactive/csr"]
hydrate = ["leptos_core/hydrate", "leptos_dom/hydrate", "leptos_reactive/hydrate"]
ssr = ["leptos_core/ssr", "leptos_dom/ssr", "leptos_reactive/ssr"]
