[package]
name = "leptos_macro"
version = "0.0.18"
edition = "2021"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/gbj/leptos"
description = "view macro for the Leptos web framework."

[lib]
proc-macro = true

[dependencies]
cfg-if = "1"
itertools = "0.10"
proc-macro-error = "1"
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full", "parsing", "extra-traits"] }
syn-rsx = "0.9"
uuid = { version = "1", features = ["v4"] }
leptos_dom = { path = "../leptos_dom", version = "0.0.18" }
leptos_reactive = { path = "../leptos_reactive", version = "0.0.18" }
lazy_static = "1.4"

[dev-dependencies]
log = "0.4"
typed-builder = "0.10"
leptos = { path = "../leptos", version = "0.0" }

[features]
default = ["ssr"]
csr = ["leptos_dom/web", "leptos_reactive/csr"]
hydrate = ["leptos_dom/web", "leptos_reactive/hydrate"]
ssr = ["leptos_reactive/ssr"]
stable = ["leptos_dom/stable", "leptos_reactive/stable"]

[package.metadata.cargo-all-features]
denylist = ["stable"]
