[package]
name = "counter-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6"
actix-web = { version = "4" }
futures = "0.3"
leptos = { path = "../../../leptos", default-features = false, features = [
	"ssr",
	"serde",
] }
leptos_router = { path = "../../../router", default-features = false, features = [
	"ssr",
] }
counter-isomorphic = { path = "../counter", default-features = false, features = [
	"ssr",
] }
lazy_static = "1"
