[package]
name = "counter-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6"
actix-web = "4"
leptos = { path = "../../../leptos", default-features = false, features = ["ssr", "serde"] }
counter-isomorphic = { path = "../counter", default-features = false, features = ["ssr"] }
