[package]
name = "leptos"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos_core = { path = "../leptos_core" }
leptos_dom = { path = "../leptos_dom" }
leptos_macro = { path = "../leptos_macro" }
leptos_reactive = { path = "../leptos_reactive" }
leptos_router = { path = "../router" }

[features]
default = ["browser", "csr"]
browser = ["leptos_router/browser", "leptos_reactive/browser"]
csr = ["leptos_macro/client"]
ssr = ["leptos_macro/ssr", "leptos_dom/server", "leptos_router/server"]
hydrate = ["leptos_macro/hydrate"]