[package]
name = "leptos"
version = "0.0.22"
edition = "2021"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/gbj/leptos"
description = "Leptos is a full-stack, isomorphic Rust web framework leveraging fine-grained reactivity to build declarative user interfaces."
readme = "../README.md"

[dependencies]
leptos_core = { path = "../leptos_core", default-features = false, version = "0.0.22" }
leptos_config = { path = "../leptos_config", default-features = false, version = "0.0.22" }
leptos_dom = { path = "../leptos_dom", default-features = false, version = "0.0.22" }
leptos_macro = { path = "../leptos_macro", default-features = false, version = "0.0.22" }
leptos_reactive = { path = "../leptos_reactive", default-features = false, version = "0.0.22" }
leptos_server = { path = "../leptos_server", default-features = false, version = "0.0.22" }

[build-dependencies]
rustc_version = "0.4"

[features]
default = ["csr", "serde", "interning"]
csr = [
  "leptos_core/csr",
  "leptos_dom/csr",
  "leptos_macro/csr",
  "leptos_reactive/csr",
  "leptos_server/csr",
]
hydrate = [
  "leptos_core/hydrate",
  "leptos_dom/hydrate",
  "leptos_macro/hydrate",
  "leptos_reactive/hydrate",
  "leptos_server/hydrate",
]
ssr = [
  "leptos_core/ssr",
  "leptos_dom/ssr",
  "leptos_macro/ssr",
  "leptos_reactive/ssr",
  "leptos_server/ssr",
]
stable = [
  "leptos_core/stable",
  "leptos_dom/stable",
  "leptos_macro/stable",
  "leptos_reactive/stable",
  "leptos_server/stable",
]
serde = ["leptos_reactive/serde"]
serde-lite = ["leptos_reactive/serde-lite"]
miniserde = ["leptos_reactive/miniserde"]
interning = ["leptos_dom/interning"]

[package.metadata.cargo-all-features]
denylist = ["stable", "interning"]
skip_feature_sets = [
  [
    "csr",
    "ssr",
  ],
  [
    "csr",
    "hydrate",
  ],
  [
    "ssr",
    "hydrate",
  ],
  [
    "serde",
    "serde-lite",
  ],
  [
    "serde-lite",
    "miniserde",
  ],
  [
    "serde",
    "miniserde",
  ],
]
