[package]
name = "counters_stable"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { path = "../../leptos", default-features = false, features = ["stable", "csr"] }
log = "0.4"
console_log = "0.2"

[dev-dependencies]
wasm-bindgen-test = "0.3.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'