[package]
name = "leptos_server"
version = "0.0.10"
edition = "2021"

[dependencies]
leptos_dom = { path = "../leptos_dom", default-features = false, version = "0.0.10" }
leptos_reactive = { path = "../leptos_reactive", default-features = false, version = "0.0.10" }
async-trait = "0.1"
gloo-net = { version = "0.2", optional = true }
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
serde_urlencoded = "0.7"
thiserror = "1"

[features]
csr = ["leptos_dom/csr", "leptos_reactive/csr", "dep:gloo-net"]
hydrate = ["leptos_dom/hydrate", "leptos_reactive/hydrate", "dep:gloo-net"]
ssr = ["leptos_dom/ssr", "leptos_reactive/ssr"]
stable = ["leptos_dom/stable", "leptos_reactive/stable"]