[package]
name = "leptos_server"
version = "0.0.12"
edition = "2021"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/gbj/leptos"
description = "RPC for the Leptos web framework."

[dependencies]
leptos_dom = { path = "../leptos_dom", default-features = false, version = "0.0.12" }
leptos_reactive = { path = "../leptos_reactive", default-features = false, version = "0.0.12" }
form_urlencoded = "1"
gloo-net = "0.2"
lazy_static = "1"
linear-map = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "1"

[dev-dependencies]
leptos_macro = { path = "../leptos_macro", default-features = false, version = "0.0.12" }
leptos = { path = "../leptos", default-features = false, version = "0.0.12" }

[features]
csr = ["leptos_dom/csr", "leptos_reactive/csr"]
hydrate = ["leptos_dom/hydrate", "leptos_reactive/hydrate"]
ssr = ["leptos_dom/ssr", "leptos_reactive/ssr"]
stable = ["leptos_dom/stable", "leptos_reactive/stable"]

[package.metadata.cargo-all-features]
denylist = ["stable"]
