[package]
name = "benchmarks"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
leptos = { path = "../leptos", default-features = false, features = ["ssr"] }
sycamore = { version = "0.8", features = ["ssr"] }
yew = { git = "https://github.com/yewstack/yew", features = ["ssr", "tokio"] }
tokio-test = "0.4"