[package]
name = "hackernews-app"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
console_log = "0.2"
leptos = { path = "../../../leptos" }
log = "0.4"
gloo-net = { version = "0.2", features = ["http"] }
reqwest = { version = "0.11", features = ["json"], optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wee_alloc = "0.4"

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'

[features]
csr = ["leptos/csr"]
hydrate = ["leptos/hydrate"]
ssr = ["leptos/ssr", "dep:reqwest"]
