[package]
name = "leptos_config"
version = "0.0.1"
edition = "2021"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/gbj/leptos"
description = "Configuraiton for Leptos"

[dependencies]
typed-builder = "0.11.0"
